name: Diagrams

on:
  push:
    paths:
      - '**/*.mermaid'
      - '**/*.md'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reasone for Manual Build'
        required: false
        default: '🧩'

jobs:
  Diagrams:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ github.event.inputs.reason }}"
    - uses: actions/checkout@v2.3.1
    - uses: neenjaw/compile-mermaid-markdown-action@master
      with:
        files: './examples/*.md'
    - uses: actions/upload-artifact@v2
      with:
        name: example/*.svg
        path: diagrams/
