name Diagrams

on
  push:
    paths:
      - '**/*.mermaid'
      - '**/*.md'

job:
  Diagrams:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: neenjaw/compile-mermaid-markdown-action@master
      with:
        files: './examples/*.md'
    - uses: actions/upload-artifact@v2
      with:
        name: example/*.svg
        path: diagrams/
